version: '2'
services:
    db:
        image: mysql:5.7
        volumes:
        - ./database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
        - db
        image: wordpress:latest
        links:
        - db
        ports:
        - "8000:80"
        volumes:
        - ./code:/code
        - ./html:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: wordpress

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - "8080:80"
        links:
        - db
        environment:
            PMA_HOST: db